config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  get :settings, controller: :home, action: :settings
  resources :profile, only: [:edit, :update] do
    collection do
      get :change_password
      post :update_password
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w[admin manager user]

  validates :role, presence: true
  validates :role, inclusion: { in: ROLES }

  def mark_as_deleted!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:index]

  def index
  end

  def settings
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def edit
    @profile = current_user
  end

  def update
    if current_user.update_attributes(params[:profile_update_params])
      redirect_to settings_path, notice: 'Profile updated successfully'
    else
      render 'edit'
    end
  end

  def change_password
  end

  def update_password
    if current_user.update_attributes(params[:password_params])
      redirect_to settings_path, notice: 'Profile updated successfully'
    else
      render 'edit'
    end
  end

  private

  def profile_update_params
    params.require(:user).permit(:name)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)

    @user.password = @user.password_confirmation = SecureRandom.hex[0..8]

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(update_user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.mark_as_deleted!
    redirect_to users_path, alert: "User <#{@user.email}> deleted successfully."
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :role)
  end

  def update_user_params
    params.require(:user).permit(:email, :role)
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time(time)
    time && time_ago_in_words(time)
  end
end

app/views/home/index.erb
<p>Trowel</p>
<p>Trowel</p>
<p>Trowel</p>
<p>Trowel</p>
<p>Trowel</p>
<p>Trowel</p>

app/views/home/settings.erb
<p>Settings</p>

<p><%= link_to 'Users', users_path %></p>
<p><%= link_to 'Edit profile', edit_profile_path(current_user) %></p>
<p><%= link_to 'Change password', change_password_profile_index_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trowel</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container">

      <% if alert.present? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Alert!</h4>
          <%= alert %>
        </div>
      <% end %>

      <% if notice.present? %>
        <div class="alert alert-block">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Notice</h4>
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="/">TrowelCI</a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Settings', settings_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/users/_form.erb
<div class="form">
  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :role %>
      <%= f.select :role, User::ROLES %>
    </div>
    <div class="field">
      <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.erb
<%= render 'form' %>

app/views/users/index.erb
<div class="pull-right">
  <%= link_to 'Back', settings_path, class: 'btn btn-default' %>
  <%= link_to 'Add', new_user_path, class: 'btn btn-default' %>
</div>

<table class="table table-striped" >
  <thead>
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Logins</th>
    <th>Current Login At</th>
    <th>Last Login At</th>
    <th>Current Login IP</th>
    <th>Last Login IP</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to(user.email, user_path(user)) %></td>
        <td><%= user.role %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= format_time(user.current_sign_in_at) %></td>
        <td><%= format_time(user.last_sign_in_at) %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.erb
<%= render 'form' %>

app/views/users/show.erb
<div class="pull-right">
  <%= link_to 'Back', users_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' %>
</div>

<p>
  Email <b><%= @user.email %></b> created on <%= @user.created_at.strftime('%d-%b-%Y') %>
</p>

<p>
  Role <b><%= @user.role %></b>
</p>

<p>
  Sign in count <b><%= @user.sign_in_count %></b>
</p>

<p>
  <div>Current sign in details </div>
  <div>Sign in <b><%= format_time(@user.current_sign_in_at) %></b> from <b><%= @user.current_sign_in_ip %></b></div>
</p>

<p>
  <div>Last sign in details </div>
  <div>Last sign in <b><%= format_time(@user.last_sign_in_at) %></b> from <b><%= @user.last_sign_in_ip %></b> </div>
</p>

<p>
  <%= link_to 'Delete this user', user_path(@user), class: 'btn btn-default btn-danger', method: :delete, data: { confirm: 'Are you sure want to delete this user ?' } %>
</p>